name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10'

    - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      uses: actions/cache@v2
      with:
        path: |
	  ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}

    - name: Install dependencies
      run: |
        cabal update
        cabal build -j --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run: cabal build -j --enable-tests --enable-benchmarks all

    - name: Run tests
      run: cabal test all
